theme: jekyll-theme-slate

title: Voting Programs
description: This is a website for sharing the code for my voting programs, including programs searching for Monotonicity, Condorcet, IAS/PI, and No-show anomalies.  If you want to view the code, click "View on Github" above.
